#!/usr/bin/env python3
"""
Test script for HTML to Markdown conversion functionality.
Creates sample HTML files and tests conversion methods.
"""

import os
import sys
import tempfile
import shutil
import base64
from pathlib import Path


def create_test_html_simple():
    """Create a simple test HTML file."""
    return """<!DOCTYPE html>
<html>
<head>
    <title>Test Document</title>
    <style>body { font-family: sans-serif; }</style>
    <script>console.log("hello");</script>
</head>
<body>
<h1>Test Document</h1>
<p>This is a <strong>test paragraph</strong> with some <em>formatted text</em>.</p>
<h2>Section 2</h2>
<p>Another paragraph with a <a href="https://example.com">link</a>.</p>
<ul>
<li>Item one</li>
<li>Item two</li>
<li>Item three</li>
</ul>
<table>
<tr><th>Name</th><th>Value</th></tr>
<tr><td>Alpha</td><td>1</td></tr>
<tr><td>Beta</td><td>2</td></tr>
</table>
</body>
</html>"""


def create_test_html_quarto():
    """Create a Quarto-like HTML file with boilerplate."""
    return """<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta charset="utf-8"/>
<title>Quarto Analysis</title>
<style>
.quarto-title { font-size: 2em; }
.sidebar { display: none; }
/* lots of CSS */
</style>
<script src="site_libs/quarto.js"></script>
<link rel="stylesheet" href="site_libs/bootstrap.css"/>
</head>
<body>
<nav id="quarto-sidebar">
<ul><li>Nav item 1</li><li>Nav item 2</li></ul>
</nav>
<div id="quarto-content">
<header>
<h1 class="title">Analysis Results</h1>
<p class="author">Test Author</p>
</header>
<section id="introduction">
<h2>Introduction</h2>
<p>This analysis examines the relationship between X and Y.</p>
</section>
<section id="results">
<h2>Results</h2>
<p>The model achieved an <strong>AUC of 0.85</strong>.</p>
<pre><code class="language-python">import pandas as pd
df = pd.read_csv("data.csv")
print(df.head())</code></pre>
<h3>Table 1: Summary Statistics</h3>
<table>
<tr><th>Variable</th><th>Mean</th><th>SD</th></tr>
<tr><td>Age</td><td>45.2</td><td>12.3</td></tr>
<tr><td>Score</td><td>78.5</td><td>15.1</td></tr>
</table>
</section>
<section id="conclusion">
<h2>Conclusion</h2>
<p>The results support our hypothesis.</p>
</section>
</div>
<footer>Generated by Quarto</footer>
<script>/* more JS */</script>
</body>
</html>"""


def create_test_html_with_images():
    """Create an HTML file with base64-encoded images."""
    # Create a tiny 1x1 red PNG
    import struct
    import zlib

    def create_minimal_png():
        """Create a minimal 1x1 red PNG image."""
        # PNG signature
        signature = b'\x89PNG\r\n\x1a\n'

        # IHDR chunk
        ihdr_data = struct.pack('>IIBBBBB', 1, 1, 8, 2, 0, 0, 0)  # 1x1, 8-bit RGB
        ihdr_crc = zlib.crc32(b'IHDR' + ihdr_data) & 0xffffffff
        ihdr = struct.pack('>I', 13) + b'IHDR' + ihdr_data + struct.pack('>I', ihdr_crc)

        # IDAT chunk (1x1 red pixel)
        raw_data = b'\x00\xff\x00\x00'  # filter byte + RGB
        compressed = zlib.compress(raw_data)
        idat_crc = zlib.crc32(b'IDAT' + compressed) & 0xffffffff
        idat = struct.pack('>I', len(compressed)) + b'IDAT' + compressed + struct.pack('>I', idat_crc)

        # IEND chunk
        iend_crc = zlib.crc32(b'IEND') & 0xffffffff
        iend = struct.pack('>I', 0) + b'IEND' + struct.pack('>I', iend_crc)

        return signature + ihdr + idat + iend

    png_data = create_minimal_png()
    b64_image = base64.b64encode(png_data).decode('ascii')

    return f"""<!DOCTYPE html>
<html>
<body>
<h1>Document with Images</h1>
<p>Here is an inline image:</p>
<img src="data:image/png;base64,{b64_image}" alt="Test Red Pixel" />
<p>And another image:</p>
<img src="data:image/png;base64,{b64_image}" alt="Another Image" />
<p>End of document.</p>
</body>
</html>"""


def test_boilerplate_stripping():
    """Test HTML boilerplate stripping."""
    print("\n=== Testing Boilerplate Stripping ===")

    try:
        from txtarchive.html_converter import strip_html_boilerplate
    except ImportError as e:
        print(f"Failed to import html_converter: {e}")
        return False

    # Test Quarto content extraction
    quarto_html = create_test_html_quarto()
    stripped = strip_html_boilerplate(quarto_html)

    checks = [
        ("Script removed", "<script" not in stripped),
        ("Style removed", "<style" not in stripped),
        ("Nav removed", "<nav" not in stripped),
        ("Footer removed", "<footer" not in stripped),
        ("Content preserved", "Analysis Results" in stripped or "Introduction" in stripped),
        ("Code preserved", "pandas" in stripped or "pd.read_csv" in stripped),
    ]

    all_passed = True
    for name, passed in checks:
        status = "PASS" if passed else "FAIL"
        print(f"  {status}: {name}")
        if not passed:
            all_passed = False

    return all_passed


def test_base64_image_extraction():
    """Test base64 image extraction."""
    print("\n=== Testing Base64 Image Extraction ===")

    try:
        from txtarchive.html_converter import extract_base64_images, _replace_base64_with_placeholders
    except ImportError as e:
        print(f"Failed to import html_converter: {e}")
        return False

    test_dir = Path(tempfile.mkdtemp(prefix="html_img_test_"))
    all_passed = True

    try:
        html_content = create_test_html_with_images()

        # Test file-based extraction
        modified_html, paths = extract_base64_images(html_content, test_dir / "images", "test")
        checks = [
            ("Images extracted", len(paths) == 2),
            ("Files created", all(p.exists() for p in paths)),
            ("Base64 removed from HTML", "data:image" not in modified_html),
            ("Markdown refs added", "![" in modified_html),
        ]

        for name, passed in checks:
            status = "PASS" if passed else "FAIL"
            print(f"  {status}: {name}")
            if not passed:
                all_passed = False

        # Test placeholder mode
        placeholder_html = _replace_base64_with_placeholders(html_content)
        placeholder_checks = [
            ("Placeholders added", "[Image" in placeholder_html),
            ("Base64 removed", "data:image" not in placeholder_html),
            ("Size info present", "KB" in placeholder_html or "bytes" in placeholder_html),
        ]

        for name, passed in placeholder_checks:
            status = "PASS" if passed else "FAIL"
            print(f"  {status}: {name}")
            if not passed:
                all_passed = False

    finally:
        shutil.rmtree(test_dir)

    return all_passed


def test_pandoc_conversion():
    """Test pandoc-based conversion."""
    print("\n=== Testing Pandoc Conversion ===")

    try:
        from txtarchive.html_converter import convert_html_with_pandoc, PANDOC_AVAILABLE
    except ImportError as e:
        print(f"Failed to import html_converter: {e}")
        return False

    if not PANDOC_AVAILABLE:
        print("  SKIP: pandoc not available")
        return True  # Not a failure, just not testable

    html = "<h1>Title</h1><p>Some <strong>bold</strong> text.</p>"

    try:
        result = convert_html_with_pandoc(html)
        checks = [
            ("Has heading", "# Title" in result or "Title" in result),
            ("Has bold", "**bold**" in result),
            ("Has text", "text" in result),
        ]

        all_passed = True
        for name, passed in checks:
            status = "PASS" if passed else "FAIL"
            print(f"  {status}: {name}")
            if not passed:
                all_passed = False
        return all_passed

    except Exception as e:
        print(f"  FAIL: pandoc conversion raised: {e}")
        return False


def test_regex_conversion():
    """Test regex-based conversion."""
    print("\n=== Testing Regex Conversion ===")

    try:
        from txtarchive.html_converter import convert_html_with_regex
    except ImportError as e:
        print(f"Failed to import html_converter: {e}")
        return False

    html = create_test_html_simple()
    # Strip outer tags for regex converter (it expects content, not full doc)
    import re
    body_match = re.search(r'<body[^>]*>(.*?)</body>', html, flags=re.DOTALL)
    body_html = body_match.group(1) if body_match else html

    result = convert_html_with_regex(body_html)

    checks = [
        ("Has heading", "# Test Document" in result),
        ("Has bold", "**test paragraph**" in result),
        ("Has italic", "*formatted text*" in result),
        ("Has link", "[link](https://example.com)" in result),
        ("Has list items", "- Item one" in result),
        ("Has table", "| Name | Value |" in result),
        ("No HTML tags", "<p>" not in result and "<h1>" not in result),
    ]

    all_passed = True
    for name, passed in checks:
        status = "PASS" if passed else "FAIL"
        print(f"  {status}: {name}")
        if not passed:
            all_passed = False

    return all_passed


def test_full_conversion():
    """Test the full orchestrator function."""
    print("\n=== Testing Full Conversion (File-based) ===")

    try:
        from txtarchive.html_converter import convert_html_to_markdown
    except ImportError as e:
        print(f"Failed to import html_converter: {e}")
        return False

    test_dir = Path(tempfile.mkdtemp(prefix="html_full_test_"))
    all_passed = True

    try:
        # Write test HTML file
        html_path = test_dir / "test.html"
        html_path.write_text(create_test_html_quarto(), encoding='utf-8')

        # Convert
        result = convert_html_to_markdown(html_path, extract_images=False)

        checks = [
            ("Non-empty result", len(result) > 0),
            ("Contains content", "Introduction" in result or "Results" in result),
            ("Script removed", "console.log" not in result),
            ("Much smaller than HTML", len(result) < len(html_path.read_text()) * 0.8),
        ]

        for name, passed in checks:
            status = "PASS" if passed else "FAIL"
            print(f"  {status}: {name}")
            if not passed:
                all_passed = False

        print(f"  Info: HTML size={len(html_path.read_text())}, MD size={len(result)}")

    finally:
        shutil.rmtree(test_dir)

    return all_passed


def test_in_memory_conversion():
    """Test the in-memory conversion for archive integration."""
    print("\n=== Testing In-Memory Conversion ===")

    try:
        from txtarchive.html_converter import convert_html_to_markdown_text
    except ImportError as e:
        print(f"Failed to import html_converter: {e}")
        return False

    html = create_test_html_with_images()
    result = convert_html_to_markdown_text(html)

    checks = [
        ("Non-empty result", len(result) > 0),
        ("No base64 data", "data:image" not in result),
        ("Image placeholders", "[Image" in result),
        ("Content preserved", "Document with Images" in result or "inline image" in result),
    ]

    all_passed = True
    for name, passed in checks:
        status = "PASS" if passed else "FAIL"
        print(f"  {status}: {name}")
        if not passed:
            all_passed = False

    return all_passed


def test_cli_integration():
    """Test the CLI convert-html subcommand."""
    print("\n=== Testing CLI Integration ===")

    test_dir = Path(tempfile.mkdtemp(prefix="html_cli_test_"))

    try:
        import subprocess

        # Write test HTML
        html_path = test_dir / "test.html"
        html_path.write_text(create_test_html_simple(), encoding='utf-8')

        output_path = test_dir / "test.md"

        cmd = [
            sys.executable, "-m", "txtarchive", "convert-html",
            str(html_path),
            str(output_path),
            "--method", "auto",
            "--no-extract-images"
        ]

        print(f"  Running: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)

        if result.returncode == 0 and output_path.exists():
            content = output_path.read_text()
            print(f"  PASS: CLI conversion succeeded ({len(content)} chars)")
            return True
        else:
            print(f"  FAIL: CLI conversion failed (rc={result.returncode})")
            if result.stderr:
                print(f"  stderr: {result.stderr[:500]}")
            return False

    except Exception as e:
        print(f"  FAIL: CLI test raised: {e}")
        return False

    finally:
        shutil.rmtree(test_dir)


def test_archive_integration():
    """Test HTML conversion during archive creation."""
    print("\n=== Testing Archive Integration ===")

    test_dir = Path(tempfile.mkdtemp(prefix="html_archive_test_"))

    try:
        from txtarchive.packunpack import archive_files

        # Create a directory with an HTML file
        src_dir = test_dir / "source"
        src_dir.mkdir()
        html_path = src_dir / "analysis.html"
        html_path.write_text(create_test_html_simple(), encoding='utf-8')

        # Also add a plain text file
        txt_path = src_dir / "readme.txt"
        txt_path.write_text("This is a readme.", encoding='utf-8')

        # Archive with .html included
        archive_path = test_dir / "archive.txt"
        archive_files(
            directory=src_dir,
            output_file_path=archive_path,
            file_types=['.html', '.txt'],
            llm_friendly=True
        )

        archive_content = archive_path.read_text()

        checks = [
            ("Archive created", archive_path.exists()),
            ("Contains file entry", "analysis.html" in archive_content),
            ("HTML converted to MD", "<h1>" not in archive_content or "# Test Document" in archive_content),
            ("No script tags", "<script>" not in archive_content),
            ("Readme included", "This is a readme" in archive_content),
        ]

        all_passed = True
        for name, passed in checks:
            status = "PASS" if passed else "FAIL"
            print(f"  {status}: {name}")
            if not passed:
                all_passed = False

        return all_passed

    except Exception as e:
        print(f"  FAIL: Archive integration test raised: {e}")
        return False

    finally:
        shutil.rmtree(test_dir)


def run_html_conversion_tests():
    """Run all HTML conversion tests."""
    print("Starting HTML Conversion Tests for TxtArchive")
    print("=" * 50)

    tests = [
        ("Boilerplate Stripping", test_boilerplate_stripping),
        ("Base64 Image Extraction", test_base64_image_extraction),
        ("Pandoc Conversion", test_pandoc_conversion),
        ("Regex Conversion", test_regex_conversion),
        ("Full Conversion", test_full_conversion),
        ("In-Memory Conversion", test_in_memory_conversion),
        ("CLI Integration", test_cli_integration),
        ("Archive Integration", test_archive_integration),
    ]

    results = []

    for test_name, test_func in tests:
        print(f"\n{'='*20} {test_name} {'='*20}")
        try:
            result = test_func()
            results.append((test_name, result))
        except Exception as e:
            print(f"  EXCEPTION: {e}")
            results.append((test_name, False))

    # Print summary
    print("\n" + "=" * 50)
    print("HTML CONVERSION TEST SUMMARY")
    print("=" * 50)

    passed = sum(1 for _, result in results if result)
    failed = len(results) - passed

    for test_name, result in results:
        status = "PASS" if result else "FAIL"
        print(f"  {test_name}: {status}")

    print(f"\nTotal: {len(results)} tests, Passed: {passed}, Failed: {failed}")

    if failed == 0:
        print("\nAll HTML conversion tests passed!")
    else:
        print(f"\n{failed} test(s) failed")

    return failed == 0


if __name__ == "__main__":
    success = run_html_conversion_tests()
    sys.exit(0 if success else 1)
